== Migration Guide

=== 1. Update dependency

Remove `eventhubs binder` dependencies.

[source,yaml]
----
<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>spring-cloud-azure-stream-binder-eventhubs</artifactId>
</dependency>
----
Add `dapr binder` dependencies.

[source,yaml]
----
<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>spring-cloud-stream-binder-dapr</artifactId>
</dependency>
----

=== 2. Update application.yaml

- Remove all configurations prefixed with `spring.cloud.azure.eventhubs.`.
- Remove all configurations prefixed with `spring.cloud.stream.eventhubs.`.
- Add configurations prefixed with `spring.cloud.stream.dapr.` and specify pubsubName.

The final eventhubs.yaml is as follows:

- `spring.cloud.stream.bindings.<binding>.destination` is configured the topic specified for sending messages.
- `spring.cloud.stream.dapr.bindings.<binding>.producer.pubsubName` is configured the name of the pub/sub component specified for sending messages.

[source,yaml]
----
spring:
  cloud:
    stream:
      function:
        definition: supply
      bindings:
        supply-out-0:
          destination: topic
      dapr:
        bindings:
          supply-out-0:
            producer:
              pubsubName: eventhubs-pubsub
----

=== 3. Configure Azure Event Hubs pubsub

Follow the instructions https://docs.microsoft.com/zh-cn/azure/event-hubs/event-hubs-create[here] on setting up Azure Event Hubs. Since this implementation uses the Event Processor Host, you will also need an https://docs.microsoft.com/zh-cn/azure/storage/common/storage-account-create?tabs=azure-portal[Azure Storage Account].

See https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-get-connection-string[here] on how to get the Event Hubs connection string. Note this is not the Event Hubs namespace.

NOTE: To setup Azure Event Hubs pubsub create a component of type `pubsub.azure.eventhubs`. See https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/#step-1-setup-the-pubsub-component[this guide] on how to create and apply a pubsub configuration.

[source,yaml]
----
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eventhubs-pubsub
  namespace: default
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://{EventHubNamespace}.servicebus.windows.net/;SharedAccessKeyName={PolicyName};SharedAccessKey={Key};EntityPath={EventHub}"
  - name: storageAccountName
    value: "***"
  - name: storageAccountKey
    value: "***"
  - name: storageContainerName
    value: "***"
----

=== 4. Run application

[source,shell]
----
dapr run --app-id publisher --app-port 9090 --components-path ${componentsPath}  --app-protocol grpc --dapr-grpc-port ${daprPort} mvn spring-boot:run
----

- `componentsPath` specify the folder location to store the component yaml files.
- `daprPort` needs to be consistent with the configuration of `spring.cloud.stream.dapr.binder.daprPort`, the default is 50001.

=== 5. Stop application

[source,shell]
----
dapr stop --app-id publisher
----
